apiVersion: v1
kind: Service
metadata:
  name: {{ include "flight-ibis.fullname" . }}-http
  labels:
    {{- include "flight-ibis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flight-ibis.selectorLabels" . | nindent 4 }}
