apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flight-ibis.fullname" . }}-secret
  labels:
    {{- include "flight-ibis.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "secrets/opaque/*").AsSecrets | indent 2 }}
