apiVersion: v1
kind: Service
metadata:
  name: {{ include "flight-ibis.fullname" . }}
  labels:
    {{- include "flight-ibis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: flight
      protocol: TCP
      name: flight
  selector:
    {{- include "flight-ibis.selectorLabels" . | nindent 4 }}
