apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flight-ibis.fullname" . }}-tls-secret
  labels:
    {{- include "flight-ibis.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "secrets/tls/*").AsSecrets | indent 2 }}
